version: '3'
services:
  frontend: 
    build:
      context: client
      dockfile: Dockerfile
    depends_on: 
      - backend
    stdin_open: true
    ports:
      - 3000:3000

  backend:
    build:
      context: backend
      dockfile: Dockerfile
    enviroment:
      MONGODB__URI: ''
      PORT: 5000
    ports:
      - 5000:5000